import os
import io
import csv
import zipfile
import sqlite3
from datetime import datetime
from flask import Flask, render_template, request, send_file, session
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()
app = Flask(__name__)
app.config['SECRET_KEY'] = os.environ.get('SESSION_SECRET', 'dev-secret-key')

# ---------- DATABASE SETUP ----------
DB_FILE = "users.db"

def init_db():
    conn = sqlite3.connect(DB_FILE)
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS users
                 (id INTEGER PRIMARY KEY AUTOINCREMENT,
                  email TEXT NOT NULL,
                  role TEXT,
                  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP)''')
    conn.commit()
    conn.close()

init_db()

# ---------- STARTUP IDEA PROMPTS ----------
startup_prompt_groups = {
    "Startup Idea Starters": [
        "Build an AI Resume Builder with ATS optimization and Stripe payments",
        "Create an AI Storybook Creator that turns prompts into illustrated books with PDF export",
        "Build a Doctor Appointment Scheduler with Twilio SMS + Retell AI calls",
        "Create a Smart Shop Platform with Shopify API + AI product descriptions",
        "Generate a Viral Waitlist SaaS with referral campaigns and email capture",
        "Build a Sales CRM SaaS with AI-powered lead scoring and outreach automation",
        "Create an Invoice Generator Pro with branded templates and tax compliance rules",
        "Build a Kanban Flow SaaS with AI task suggestions & automation",
        "Create a Project Management Lite app with AI task summaries",
        "Build an Expense & Finance Tracker with Plaid API + AI insights",
        "Create a Customer Segmentation Dashboard with clustering & visualization",
        "Build a Fintech Dashboard for real-time transaction analytics",
        "Create an Ergonomics Research Dashboard with IoT wearables API",
        "Build a Content Tracking Dashboard for digital asset usage",
        "Create a Legal AI contract analyzer with compliance flagging",
        "Build an AI Cognitive Insights Dashboard for reasoning pattern analysis",
        "Create a Mental Health Platform with journaling + AI chatbot",
        "Build a Women's Safety App with SOS alerts + GPS tracking",
        "Create a Pediatric Health Tracker with growth and vaccination logs",
        "Build an AI Nutrition Coach with meal tracking and balanced diet recommendations",
        "Create a Crypto Payment Gateway with fiat + crypto support",
        "Build a Car Parts Marketplace with inventory sync",
        "Create a Luxury Goods Marketplace with escrow & NFT provenance",
        "Build an AI Spreadsheet with formula auto-generation and automations",
        "Create an AI Animation Studio for drag-and-drop video creation with AI narration",
        "Build a Music Visualizer Studio synced with uploaded music",
        "Create an Interactive 3D Portfolio Builder with animated case studies",
        "Build a Metaware Logo Particles generator for brands",
        "Create an Event Gifting Platform with AI gift recommendations & logistics",
        "Build a Smart Resume Interview Coach with AI feedback on answers"
    ],
    "AI & SaaS Projects": [
        "AI Agency Landing Page — Template for marketing AI services (Next.js + Tailwind)",
        "AI Web Assistant — SaaS landing for an AI-powered chatbot (Next.js + OpenAI SDK)",
        "AI Chatbot Website — Conversational bot frontend using GPT + Supabase",
        "AI Voice Assistant UI — Voice-enabled chat interface with speech-to-text + ElevenLabs",
        "AI Elements SDK Demo — Component kit for building AI-powered UI (React + AI SDK)",
        "AI Landing Page — General AI business site template (Next.js)",
        "Sentient AI — Experimental AI personality showcase (OpenAI + React)",
        "CoolKid AI — Fun AI playground for kids with GPT + voice",
        "AI Discovery Form — Smart client intake form with AI qualification logic (Next.js + GPT)",
        "AI Resume Builder — ATS-friendly CVs generated by GPT (Next.js + Supabase)",
        "AI Spreadsheet — Spreadsheet with AI-assisted formulas (React + GPT)",
        "AI Service Landing Page — Site template for AI SaaS companies (Next.js + Tailwind)",
        "AI Prompt Builder — Interface to create and organize GPT prompts (React + OpenAI API)",
        "AI Card Generator — AI-generated digital business cards (Next.js + Vercel AI SDK)",
        "AI Kit Landing — SaaS starter kit template for AI agencies (Next.js + ShadCN)",
        "AI Alan Watts Blog — Auto-generated philosophy-style blog posts (OpenAI + Next.js)",
        "AI Prompt Project Builder — Workflow app to design GPT projects (React + Supabase)",
        "AI Dashboard — Analytics + insights SaaS template (Next.js + Supabase)",
        "AI Columns Design — AI-driven dynamic content layouts (Next.js + Tailwind)",
        "AI Nutrition Coach — Personalized diet recommendations with GPT + Spoonacular API",
        "AI Dentist Receptionist — Automated dental booking via phone (Twilio + Retell AI)",
        "Legal AI — Contract/compliance analyzer using GPT + Pinecone",
        "AI Trading Platform — Algo-trading dashboard with GPT insights (Web3 API + React)",
        "AI Storybook Creator — Generates illustrated kids' stories (GPT + DALL·E + ElevenLabs)",
        "AI Cognitive Fallacy Index — Explains biases/fallacies with GPT",
        "AI Robotics Landing Page — Showcase site for AI + robotics startups (Next.js)",
        "AI SaaS Landing Hero with Video — Marketing site with AI demo background (Next.js + video.js)",
        "AI Music Converter — Converts audio styles with ML (TensorFlow + WebAudio API)",
        "AI Job Matching Platform — Matches resumes to job postings with GPT embeddings",
        "CodeHope – AI Coding Assistant — Copilot-like tool for devs (GPT + VSCode API)",
        "AI SDK Starter — Boilerplate for building apps with AI SDK (Next.js + Vercel AI SDK)",
        "AI Powered Animation Studio — Animations generated via GPT prompts (Three.js + OpenAI)",
        "AI Chat UI Design — Demo for integrating chatbots into apps (React + Tailwind)",
        "AI Blog Generator — Auto-blog writer with GPT + Supabase",
        "AI SaaS Starter — Starter kit for AI SaaS apps (Next.js + ShadCN)",
        "AI Resume ATS Checker — Checks resume scoring against ATS (OpenAI + Puppeteer)",
        "AI Platform Hero Section — Landing page hero with AI branding (Next.js)",
        "AI Story Voiceover — Narration with ElevenLabs + GPT",
        "AI Music Starter (ElevenLabs) — Generates music ideas from text prompts (GPT + Audio SDK)",
        "AI Podcast Generator — Turns text into podcast episodes (GPT + ElevenLabs)",
        "AI Music Starter v3 — Updated audio-generation starter using OpenAI TTS + Next.js",
        "AI Video Animation Page — Hero section with AI-generated video background"
    ],
    "E-Commerce & Marketplaces": [
        "Shopify Ecommerce Template — Shopify + Tailwind template for online stores",
        "Minimal Shop — Next.js + Tailwind lightweight e-commerce starter",
        "Clothing Ecommerce Platform — React + Node.js fashion storefront with cart/checkout",
        "Car Parts E-Commerce — Next.js + Express store tailored to automotive parts",
        "Crypto Payment Gateway — Web3 + Next.js + Solidity integration for digital currency checkout",
        "NFT Marketplace Website — Web3.js + Next.js NFT buy/sell platform",
        "Flexible E-Commerce Platform — Full-stack Next.js + Stripe + Supabase backend",
        "E-Commerce Website Design — Tailwind + React pre-styled shopping pages",
        "Complete E-Commerce Website — Next.js + Prisma + Stripe checkout full solution",
        "E-Commerce Online Shopping App — React Native + Firebase mobile shopping app",
        "Food POS & Online Store — POS + ordering dashboard using React + Supabase",
        "Luxury Portfolio Storefront — Modern Tailwind e-commerce with product galleries",
        "Single Product QuickShop (EN+AR) — Next.js + Stripe + i18n bilingual store",
        "Farmers Market Website — Local food marketplace built with WordPress + WooCommerce",
        "Art Auction Platform — Next.js + WebSockets for real-time bidding",
        "Furniture & Home Decor E-Commerce — Shopify/Next.js hybrid storefront",
        "Mobile Storefront (Nano Banana) — Next.js + AI SDK + AI Gateway experimental commerce",
        "Bookstore Template — React + Supabase bookstore front with payments",
        "Digital Marketplace (Productized Services) — Next.js + Stripe for SaaS service selling",
        "Marketplace Template — Next.js + Shadcn base marketplace starter",
        "Supabase Mini Ecommerce — Supabase + React minimal e-commerce setup",
        "Supabase Starter Shop — Supabase + Tailwind + Stripe starter store",
        "Modern Tote Bag Store — Tailwind + React styled single-product shop",
        "Shopify Product Page Design — Shopify + Liquid + Tailwind styled PDP layout",
        "Shopify Template (Alt) — Duplicate Shopify layout, Shopify + Tailwind",
        "E-Commerce Platform Idea — Next.js + Stripe generic e-commerce scaffold",
        "Nanga Market E-Commerce — WordPress + WooCommerce regional market site",
        "Origin E-Commerce UI — Tailwind + Shadcn pre-built components for online stores",
        "E-Commerce App (Mobile) — React Native e-commerce app with Firebase backend",
        "E-Commerce Website Clone — Next.js full-stack clone of a modern store",
        "Amazon E-Commerce Site Clone — Next.js + Supabase Amazon-style storefront",
        "Skylab Token Store (Test) — Next.js + Web3.js token-based marketplace",
        "Crypto Vest Platform — Blockchain + React investment/e-commerce hybrid",
        "Car Rental Website Clone — Next.js + Tailwind car rental e-commerce design",
        "Booking Car Rent App — React Native + Stripe car rental booking system",
        "Hotel Booking E-Commerce — Next.js + Supabase hotel booking platform",
        "Restaurant Recruitment Platform — Job + booking style hybrid, Next.js + Supabase",
        "Pizza Shop Website — Tailwind + Next.js small restaurant ordering site",
        "Coffee Shop Inventory System — Supabase + Prisma coffee store management",
        "Bakery Landing Page — Next.js + Tailwind e-commerce landing",
        "Café & Bistro E-Commerce — WordPress + WooCommerce for small cafés",
        "Sapid Food Ordering — Mobile food ordering app, React Native + Firebase",
        "Food POS Dashboard (Keeping Food) — React POS + ordering for restaurants",
        "Teatree Website Redesign — Tailwind + WordPress template for cafés",
        "Fit Life E-Commerce — Next.js + Stripe fitness & wellness store",
        "Wellness Product Store — Shopify + Tailwind supplements/e-commerce",
        "Beauty Website Design — Tailwind + Next.js beauty products storefront",
        "Glow Salon Booking Storefront — Next.js + Stripe salon/beauty e-commerce",
        "Cosmetics E-Commerce Platform — Shopify + Tailwind beauty store template",
        "PerfumesPedia — Next.js + WooCommerce fragrance directory/shop",
        "Tattoo E-Commerce Concept — Shopify + WooCommerce tattoo products",
        "Toy Storefront (Shivam Toys) — Next.js toy shop e-commerce site",
        "Olive Kiddies Store — Shopify children's products e-commerce",
        "Healthcare POS + Store — Supabase hospital POS + pharmacy ordering",
        "Pharmacy & Prescription Storefront — WordPress + WooCommerce + HIPAA add-ons",
        "Pet Store E-Commerce Template — Tailwind + Next.js pet store",
        "Modern Pet Store E-Commerce Template — React + Supabase styled storefront",
        "Dog Grooming Landing Storefront — Next.js + Stripe dog grooming booking + shop",
        "Herbal Garden Website — Shopify natural products store",
        "HaloCare Health Store — WordPress + HIPAA add-on online healthcare shop",
        "Hospital App E-Commerce — Next.js + Supabase hospital POS/appointments",
        "MediHomeTz E-Commerce — Next.js + Stripe healthcare storefront",
        "Dentist Monali Storefront — Tailored dental e-commerce booking",
        "Pediatric Health App Storefront — Next.js + Firebase pediatric shop",
        "Personalized Meal Delivery App — React Native + Stripe subscription meal delivery",
        "Fitness Appointment App — Next.js + Stripe gym/fitness e-commerce",
        "Fitmart Mobile App — React Native + Stripe fitness store mobile app",
        "Nutrition App Storefront — Next.js + Tailwind diet plan + e-commerce integration",
        "NFeProdutor Farm Store — Agriculture-focused e-commerce app",
        "Masari Webapp Marketplace — Next.js + Supabase small marketplace app",
        "Jobhouse25 Marketplace — Job + e-commerce platform, Next.js full-stack",
        "B2B SaaS E-Commerce Starter (Clerk) — Clerk + Next.js B2B store template",
        "B2C SaaS E-Commerce Starter (Clerk) — Clerk + Next.js B2C store template",
        "SaaS Yacht Club Storefront — Next.js SaaS membership + e-commerce template",
        "Ai Service Landing Page (Store) — Next.js + Stripe AI-as-a-service checkout",
        "Sentient AI Subscription Storefront — Next.js + Stripe AI subscription e-commerce",
        "AI Kit Landing Storefront — Next.js + Stripe AI tools e-commerce",
        "Digital Art Space E-Commerce — Next.js art store with Stripe",
        "Photography Quote Calculator Storefront — Next.js app + Stripe for creative services",
        "Custom Game Card Maker Storefront — Tailwind + Stripe game merch e-commerce",
        "Music Production Site Storefront — Next.js + Supabase music digital shop",
        "Guitar Scale Practice Tool Storefront — React + Stripe SaaS e-commerce for musicians",
        "Music Visualizer E-Commerce Add-On — Creative audio tool with paid templates",
        "Spotify UI Store Clone — React + Supabase Spotify-style merch store",
        "Perfume Store (Alternate) — Shopify fragrance e-commerce template",
        "Travel Partner App Storefront — Travel + bookings + e-commerce",
        "Travel Buddy App Store — React Native travel planning + Stripe checkout",
        "Carpenter's Toolkit Storefront — Shopify tools/e-commerce shop",
        "Construction Service Website — Next.js + Stripe construction marketplace",
        "ERM Manufacturing Website — WordPress manufacturing e-commerce",
        "Auto Parts Storefront — Next.js + Stripe auto parts e-commerce",
        "Vehicle Assistant Storefront — Next.js + Supabase vehicle services shop",
        "Luxury Yacht Website Storefront — Next.js + Tailwind yacht sales e-commerce",
        "Event Gifting SuperChat — Next.js + Stripe gifting marketplace",
        "Event Gifting Ticketing — Next.js + Stripe ticket sales storefront",
        "Event Gifting Kouyasai — Cultural gift exchange marketplace, React + Supabase",
        "Ejl Farms Website Storefront — WordPress agriculture e-commerce",
        "LZ4 Playground Shop — React + Stripe digital tools store",
        "Skincare & GlowForce Products Storefront — Next.js + Stripe wellness e-commerce",
        "AI Card Generation Storefront — Next.js + AI SDK + Stripe digital card generator"
    ],
    "AI Creative & Media": [
        "Realtime Drawing to AI Image — FAL + Next.js drawing-to-image generator",
        "Image to ASCII Converter — Next.js + Node.js ASCII art image generator",
        "Brushcii ASCII Art Painter — React ASCII art painting app",
        "Image to SVG Converter — Next.js + Tailwind image vectorization tool",
        "Image to Code Pattern Generator — Next.js + Tailwind image/code transformation",
        "PNG to SVG Converter — Next.js + Tailwind quick image vectorizer",
        "Free WebP Converter — Next.js + Node.js image format converter",
        "Image-Buddy Tool — Next.js + Supabase image handling SaaS",
        "Gradient Color Images Generator — Next.js + Tailwind gradient image maker",
        "Gradient-Blind Hero Section — React + Tailwind gradient design block",
        "Shader Gradient Component — Next.js + GLSL gradient visual effect",
        "Background Paths Generator — Next.js + SVG background generator",
        "Arc Images Gallery — Next.js + Tailwind image showcase UI",
        "3D Gallery Photography Template — WebGL + Next.js 3D image gallery",
        "Dynamic Rain Website Effect — Next.js + WebGL particle animation",
        "Wavey Background Generator — React + Canvas animated wave backgrounds",
        "Beams Background Animation — Next.js + Tailwind beam animation effect",
        "Fluid Particles Background — WebGL + Canvas particle animation demo",
        "Ball Trail Animation — React + Three.js interactive trail effect",
        "Animated Beam Effect — Next.js + WebGL animated beam visualization",
        "Particle Floor Animation — WebGL + Three.js particle surface effect",
        "Swarm of Bouncing Dots — React + Canvas bouncing dot physics effect",
        "Tags Gravity Animation — React + D3.js interactive tag cloud effect",
        "Liquid Animation Effect — Next.js + Canvas liquid animation visuals",
        "Linear Canvas Ball Animation — Next.js + Canvas bouncing ball demo",
        "Interactive Waves Effect — React + Canvas wave motion generator",
        "Wave Text Animation — Next.js + Tailwind wave typography effect",
        "Dynamic Visual Representation — React + D3.js animated visualization",
        "Neon Maze Animation — Next.js + WebGL neon-style maze visualizer",
        "Corona Particle System — WebGL + Three.js particle effect demo",
        "Matrix Rain Effect — Next.js + Canvas animated Matrix-style effect",
        "Pixelated Background (Animated) — React + Tailwind retro pixel animation",
        "Starry Night MotionJS Demo — React + MotionJS starry sky animation",
        "MotionFX Particle Background — React + WebGL dynamic particle FX",
        "AI Powered Animation Studio — Next.js + AI SDK video/animation generator SaaS",
        "Logo Particles (AWS + V0) — Next.js + WebGL particle-based logo animation",
        "Metaware Logo Particles — WebGL + Tailwind particle text/logo animation",
        "Morphing Info Animation — Next.js + WebGL info block morphing",
        "Morphing Sign-In Button — Next.js + Tailwind interactive button animation",
        "Peel Effect Demo — Next.js + Giselle peel transition animation",
        "Coolest Page Transitions — React + Framer Motion advanced transitions",
        "Event Badge Animation — Next.js + Tailwind animated badge generator",
        "Accordion Animation Video Display — React + Tailwind animated accordion with video",
        "Animated File Upload — Shadcn UI + React animated file uploader",
        "Animated Music Player UI — React + Supabase audio player with animations",
        "Animated Birthday Website — Next.js + Tailwind animated birthday greetings",
        "Animated Letter Card — React + CSS animated card template",
        "Animated Paint Swatch — React + Tailwind animated paint swatches",
        "Animated Thumbnail Support — Next.js + Tailwind animated preview system",
        "Animated Carousel Component — React + Tailwind animated image slider",
        "Animated Unauthorized Page — Next.js + Tailwind animated 401/403 error page",
        "Animated Toolbar UI — React + Shadcn animated toolbar widget",
        "Animated WIP Landing Page — Next.js + Tailwind animated 'coming soon' page",
        "Creative Agency Portfolio — Next.js + Tailwind creative portfolio site template",
        "Voicetwoo Creative Portfolio — Next.js + Tailwind creative portfolio design",
        "ShopSculpt Agency Portfolio — Next.js + Tailwind creative agency site",
        "Glow Menu Component — Shadcn UI + Tailwind glowing navigation menu",
        "Liquid Glass Login Page — Next.js + Tailwind frosted glass login template",
        "Liquid Glass Navigation Menu — Next.js + Tailwind glassmorphic nav bar",
        "Liquid Glass Tabs — Next.js + Tailwind frosted glass tab navigation",
        "Frosted Glass Authentication Concept — Next.js + Tailwind login/register UI",
        "Frosted Authentication Page — Next.js + Tailwind auth landing page",
        "Frosted Apple Widget Design — Next.js + Tailwind frosted glass widget UI",
        "Frosted Dark UI Feedback Modal — Next.js + Shadcn frosted modal",
        "Glassmorphism Website Design — Next.js + Tailwind glassmorphic theme",
        "Glassmorphic Command Palette — Next.js + Shadcn frosted command palette",
        "Glassmorphic Rich Text Editor — Next.js + Tailwind text editor design",
        "Glass Frosted Product Review Form — Next.js + Shadcn frosted review form",
        "Glassmorphic Utility Page — React + Tailwind frosted utility layout",
        "Glassmorphic Item Selector — React + Shadcn frosted item selector"
    ]
}

def save_user(email, role):
    conn = sqlite3.connect(DB_FILE)
    c = conn.cursor()
    c.execute("INSERT INTO users (email, role) VALUES (?, ?)", (email, role))
    conn.commit()
    conn.close()

# ---------- OPENAI CLIENT ----------
def get_openai_client():
    api_key = os.environ.get('OPENAI_API_KEY')
    if not api_key:
        return None
    return OpenAI(api_key=api_key)

def check_api_key():
    """Check if OpenAI API key is configured"""
    return os.environ.get('OPENAI_API_KEY') is not None

# ---------- PLANNING + CODE GENERATION ----------
def hrm_plan(user_request):
    client = get_openai_client()
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You are an expert architect. Break coding requests into 4–5 subtasks."},
            {"role": "user", "content": f"Break down this request:\n{user_request}"}
        ]
    )
    subtasks_text = response.choices[0].message.content.strip()
    subtasks = [line.lstrip("0123456789.-•) ").strip() for line in subtasks_text.splitlines() if line.strip()]
    return subtasks[:5]

def generate_code(subtask, user_request):
    client = get_openai_client()
    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You are an expert engineer. Output only valid code."},
            {"role": "user", "content": f"Original request: {user_request}\nSubtask: {subtask}\nGenerate code."}
        ]
    )
    return response.choices[0].message.content.strip()

# ---------- ROUTES ----------
@app.route('/', methods=['GET', 'POST'])
def index():
    template_prompts = [
        "Build a SaaS landing page with signup and pricing",
        "Create a Flask API with JWT authentication",
        "Generate a Next.js app with Firebase auth and Stripe checkout",
        "Build a React dashboard with Tailwind and Chart.js",
        "Write a Python script to scrape a website and save results to CSV"
    ]

    if request.method == 'POST':
        user_request = request.form.get('user_request', '').strip()
        if not user_request:
            return render_template("index.html", error="Please enter a request", template_prompts=template_prompts, startup_prompt_groups=startup_prompt_groups)

        # Check if API key is configured
        if not check_api_key():
            error_msg = "⚠️ OpenAI API key is missing. Please add your OPENAI_API_KEY to the .env file to use Logora."
            return render_template("index.html", error=error_msg, user_request=user_request, template_prompts=template_prompts, startup_prompt_groups=startup_prompt_groups)

        try:
            subtasks = hrm_plan(user_request)
            results = [{"subtask": st, "code": generate_code(st, user_request)} for st in subtasks]
            # Store in Flask session for download
            session['results'] = results
            session['user_request'] = user_request
            return render_template("index.html", user_request=user_request, results=results, template_prompts=template_prompts, startup_prompt_groups=startup_prompt_groups)
        except Exception as e:
            error_msg = f"Error generating code: {str(e)}"
            return render_template("index.html", error=error_msg, user_request=user_request, template_prompts=template_prompts, startup_prompt_groups=startup_prompt_groups)

    return render_template("index.html", template_prompts=template_prompts, startup_prompt_groups=startup_prompt_groups)

@app.route('/download', methods=['POST'])
def download():
    email = request.form.get("email")
    role = request.form.get("role", "Unknown")

    if not email:
        return "Email is required to download.", 400

    # Save user info
    save_user(email, role)

    # Get session results
    user_request = session.get("user_request", "AI Project")
    results = session.get("results", [])

    if not results:
        return "No generated code to download. Please generate code first.", 400

    # Create ZIP in memory
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w") as zf:
        zf.writestr("README.md", f"# Generated Project\n\nRequest: {user_request}\n\nCreated with Logora AI")
        for idx, res in enumerate(results, 1):
            filename = f"subtask_{idx}.py"
            zf.writestr(filename, res["code"])
    zip_buffer.seek(0)

    return send_file(zip_buffer, as_attachment=True, download_name="logora_project.zip", mimetype="application/zip")

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)
